fix: generate build artifact before deploy v5
install rake due dependency chain:

```sh
In Gemfile:
  jekyll was resolved to 4.3.3, which depends on
    jekyll-sass-converter was resolved to 3.0.0, which depends on
      sass-embedded was resolved to 1.69.5, which depends on
        rake
Error: Process completed with exit code 5.
```